=== Azure/azure-functions-templates/Docs/template-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "<TEMPLATE_SCHEMA_URL>",
    "title": "Azure Functions Template",
    "description": "A template in Azure Functions' v2 template schema",
    "type": "object",

    "properties": {
        "author": {
            "description": "The author of this template (author/maintainer/owner/contact)",
            "type": "string"
        },
        "name": {
            "description": "The name of this template; usually <Trigger> ex. 'HTTP Trigger'",
            "type": "string"
        },
        "description": {
            "description": "A short description of this template's trigger's functionality",
            "type": "string"
        },
        "programmingModel": {
            "description": "The programming model the template applies to",
            "enum": [ "v1", "v2" ]
        },
        "language": {
            "description": "The programming language the template applies to",
            "enum": [ "dotnet", "node", "python", "powershell" ]
        },
        "jobs": {
            "description": "The list of jobs defined by the template, each corresponding to a user gesture",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "description": "The display name of this job",
                        "type": "string"
                    },
                    "condition": {
                        "description": "The condition that must evaluate to true to run this job",
                        "name": {
                            "description": "The name of the variable to evaluate",
                            "type": "string"
                        },
                        "expectedValue": {
                            "description": "The value for which the condition is true",
                            "type": "string"
                        }
                    },
                    "input": {
                        "description": "The input provided to the job by the user gesture in the tooling",
                        "userCommand": {
                            "description": "The identifier for a job",
                            "type": "string"
                        },
                        "assignTo": {
                            "description": "Identifier to assign initial tooling-provided input to",
                            "type": "string",
                            "pattern": "\\$\\([A-Z0-9_]+\\"
                        }
                    },
                    "actions": {
                        "description": "Names of the actions the job executes in order of operation",
                        "items": { 
                            "oneOf": [ 
                                { "type": "string" },
                                { "$ref": "<ACTION_SCHEMA_URL>" }
                            ],
                        "minItems": 1
                        }
                    },
                    "required": [ "name", "input", "actions" ]
                },
            "minItems": 1,
            "uniqueItems": true
            }
        },
        "actions": {
            "description": "The list of action definitions used by jobs defined by a template",
            "type": "array",
            "items": { "$ref": "<ACTION_SCHEMA_URL>" },
            "minItems": 1,
            "uniqueItems": true
        }
    },
    "required": [ "author", "name", "description", "programmingModel", "language", "jobs", "actions" ]
}

=== Azure/azure-functions-templates/Functions.Templates/Templates-v2/CosmosDbTrigger-Python/template.json
{
    "author": "Gavin Aguiar",
    "name": "CosmosDB trigger",
    "description": "$CosmosDBTrigger_description",
    "programmingModel": "v2",
    "language": "python",
    "jobs": [
        {
            "name": "Create New Project with CosmosDbTrigger function",
            "type": "CreateNewApp",
            "inputs": [
                {
                    "assignTo": "$(APP_FILENAME)",
                    "paramId": "app-fileName",
                    "defaultValue": "function_app.py",
                    "required": true,
                    "condition" : {
                        "name": "ClientId",
                        "values": [ "VSCode"],
                        "operator": "IN"
                    }
                },
                {
                    "assignTo": "$(FUNCTION_NAME_INPUT)",
                    "paramId": "trigger-functionName",
                    "required": true,
                    "defaultValue": "cosmosdb_trigger"
                },
                {
                    "assignTo": "$(CONTAINER_NAME_INPUT)",
                    "paramId": "cosmosDbTrigger-containerName",
                    "required": true,
                    "defaultValue": "container_name"
                },
                {
                    "assignTo": "$(DB_NAME_INPUT)",
                    "paramId": "cosmosDbTrigger-databaseName",
                    "required": true,
                    "defaultValue": "database_name"
                },
                {
                    "assignTo": "$(CONNECTION_STRING_INPUT)",
                    "paramId": "cosmosDbTrigger-connection",
                    "required": true,
                    "defaultValue": "CosmosDbConnectionString"
                }
            ],
            "actions": [
                "readFileContent_FunctionApp",
                "writeFile_FunctionApp",
                "showMarkdownPreview"
            ]
        },
        {
            "name": "Add CosmosTrigger function to the main file",
            "type": "AppendToFile",
            "inputs": [
                {
                    "assignTo": "$(SELECTED_FILEPATH)",
                    "paramId": "app-selectedFileName",
                    "defaultValue": "function_app.py",
                    "required": true,
                    "condition" : {
                        "name": "ClientId",
                        "values": [ "VSCode"],
                        "operator": "IN"
                    }
                },
                {
                    "assignTo": "$(FUNCTION_NAME_INPUT)",
                    "paramId": "trigger-functionName",
                    "required": true,
                    "defaultValue": "cosmosdb_trigger"
                },
                {
                    "assignTo": "$(CONTAINER_NAME_INPUT)",
                    "paramId": "cosmosDbTrigger-containerName",
                    "required": true,
                    "defaultValue": "container_name"
                },
                {
                    "assignTo": "$(DB_NAME_INPUT)",
                    "paramId": "cosmosDbTrigger-databaseName",
                    "required": true,
                    "defaultValue": "database_name"
                },
                {
                    "assignTo": "$(CONNECTION_STRING_INPUT)",
                    "paramId": "cosmosDbTrigger-connection",
                    "required": true,
                    "defaultValue": "CosmosDbConnectionString"
                }
            ],
            "actions": [
                "readFileContent_FunctionBody",
                "appendFileContent_FunctionApp"
            ]
        },
        {
            "name": "Create New Blueprint file",
            "type": "CreateNewBlueprint",
            "inputs": [
                {
                    "assignTo": "$(BLUEPRINT_FILENAME)",
                    "paramId": "blueprint-fileName",
                    "defaultValue": "blueprint.py",
                    "required": true,
                    "condition" : {
                        "name": "ClientId",
                        "values": [ "VSCode"],
                        "operator": "IN"
                    }
                },
                {
                    "assignTo": "$(FUNCTION_NAME_INPUT)",
                    "paramId": "trigger-functionName",
                    "required": true,
                    "defaultValue": "cosmosdb_trigger"
                },
                {
                    "assignTo": "$(CONTAINER_NAME_INPUT)",
                    "paramId": "cosmosDbTrigger-containerName",
                    "required": true,
                    "defaultValue": "container_name"
                },
                {
                    "assignTo": "$(DB_NAME_INPUT)",
                    "paramId": "cosmosDbTrigger-databaseName",
                    "required": true,
                    "defaultValue": "database_name"
                },
                {
                    "assignTo": "$(CONNECTION_STRING_INPUT)",
                    "paramId": "cosmosDbTrigger-connection",
                    "required": true,
                    "defaultValue": "CosmosDbConnectionString"
                }
            ],
            "actions": [
                "readFileContent_BlueprintFile",
                "writeFile_BlueprintFile",
                "readFileContent_BlueprintBody",
                "appendFileContent_BlueprintBody"
            ]
        },
        {
            "name": "Add CosmosDBTrigger function to the Blueprint",
            "type": "AppendToBlueprint",
            "inputs": [
                {
                    "assignTo": "$(BLUEPRINT_FILENAME)",
                    "paramId": "blueprint-existingFileName",
                    "required": true,
                    "condition" : {
                        "name": "ClientId",
                        "values": [ "VSCode"],
                        "operator": "IN"
                    }
                },
                {
                    "assignTo": "$(FUNCTION_NAME_INPUT)",
                    "paramId": "trigger-functionName",
                    "required": true,
                    "defaultValue": "cosmosdb_trigger"
                },
                {
                    "assignTo": "$(CONTAINER_NAME_INPUT)",
                    "paramId": "cosmosDbTrigger-containerName",
                    "required": true,
                    "defaultValue": "container_name"
                },
                {
                    "assignTo": "$(DB_NAME_INPUT)",
                    "paramId": "cosmosDbTrigger-databaseName",
                    "required": true,
                    "defaultValue": "database_name"
                },
                {
                    "assignTo": "$(CONNECTION_STRING_INPUT)",
                    "paramId": "cosmosDbTrigger-connection",
                    "required": true,
                    "defaultValue": "CosmosDbConnectionString"
                }
            ],
            "actions": [
                "readFileContent_BlueprintBody",
                "appendFileContent_BlueprintBody"
            ]
        }
    ],
    "actions": [
        {
            "name": "readFileContent_FunctionApp",
            "type": "GetTemplateFileContent",
            "assignTo": "$(FUNCTION_APP_CONTENT)",
            "filePath": "function_app.py"
        },
        {
            "name": "writeFile_FunctionApp",
            "type": "WriteToFile",
            "source": "$(FUNCTION_APP_CONTENT)",
            "filePath": "$(APP_FILENAME)",
            "continueOnError": false,
            "errorText": "Unable to create the function app",
            "replaceTokens": true,
            "FileExtension": ".py"
        },
        {
            "name": "readFileContent_FunctionBody",
            "type": "GetTemplateFileContent",
            "assignTo": "$(FUNCTION_BODY)",
            "filePath": "function_body.py"
        },
        {
            "name": "appendFileContent_FunctionApp",
            "type": "AppendToFile",
            "createIfNotExists": false,
            "source": "$(FUNCTION_BODY)",
            "filePath": "$(SELECTED_FILEPATH)",
            "continueOnError": false,
            "errorText": "Unable to create eventhub trigger function",
			"replaceTokens": true,
            "FileExtension": ".py"
        },
        {
            "name": "ShowMarkdownPreview",
            "type": "ShowMarkdownPreview",
            "filePath": "cosmosdb_trigger_template.md"
        },
        {
            "name": "readFileContent_BlueprintFile",
            "type": "GetTemplateFileContent",
            "assignTo": "$(BLUEPRINT_CONTENT)",
            "filePath": "blueprint.py"
        },
        {
            "name": "writeFile_BlueprintFile",
            "type": "WriteToFile",
            "source": "$(BLUEPRINT_CONTENT)",
            "filePath": "$(BLUEPRINT_FILENAME)",
            "continueOnError": false,
            "errorText": "Unable to create blueprint",
            "replaceTokens": true,
            "FileExtension": ".py"
        },
        {
            "name": "readFileContent_BlueprintBody",
            "type": "GetTemplateFileContent",
            "assignTo": "$(BLUEPRINT_BODY_CONTENT)",
            "filePath": "blueprint_body.py"
        },
        {
            "name": "appendFileContent_BlueprintBody",
            "type": "AppendToFile",
            "source": "$(BLUEPRINT_BODY_CONTENT)",
            "filePath": "$(BLUEPRINT_FILENAME)",
            "continueOnError": false,
            "errorText": "Unable to create the Blueprint",
            "replaceTokens": true,
            "FileExtension": ".py"
        }
    ]
}

=== Azure/azure-functions-templates/Functions.Templates/Templates-v2/DaprServiceInvocationTrigger-Python/template.json
{
    "author": "Ashique",
    "name": "Dapr Service Invocation Trigger",
    "description": "$DaprServiceInvocationTrigger_description",
    "programmingModel": "v2",
    "language": "python",
    "jobs": [
        {
            "name": "Create New Project with DaprServiceInvocationTrigger function",
            "type": "CreateNewApp",
            "inputs": [
                {
                    "assignTo": "$(APP_FILENAME)",
                    "paramId": "app-fileName",
                    "defaultValue": "function_app.py",
                    "required": true,
                    "condition" : {
                        "name": "ClientId",
                        "values": [ "VSCode"],
                        "operator": "IN"
                    }
                },
                {
                    "assignTo": "$(FUNCTION_NAME_INPUT)",
                    "paramId": "trigger-functionName",
                    "required": true,
                    "defaultValue": "dapr_service_invocation_trigger"
                }
            ],
            "actions": [
                "readFileContent_FunctionApp",
                "writeFile_FunctionApp",
                "showMarkdownPreview"
            ]
        },
        {
            "name": "Add DaprServiceInvocationTrigger function to the main file",
            "type": "AppendToFile",
            "inputs": [
                {
                    "assignTo": "$(SELECTED_FILEPATH)",
                    "paramId": "app-selectedFileName",
                    "defaultValue": "function_app.py",
                    "required": true,
                    "condition" : {
                        "name": "ClientId",
                        "values": [ "VSCode"],
                        "operator": "IN"
                    }
                },
                {
                    "assignTo": "$(FUNCTION_NAME_INPUT)",
                    "paramId": "trigger-functionName",
                    "required": true,
                    "defaultValue": "dapr_service_invocation_trigger"
                }
            ],
            "actions": [
                "readFileContent_FunctionBody",
                "appendFileContent_FunctionApp"
            ]
        },
        {
            "name": "Create New Blueprint file",
            "type": "CreateNewBlueprint",
            "inputs": [
                {
                    "assignTo": "$(APP_FILENAME)",
                    "paramId": "app-fileName",
                    "defaultValue": "blueprint.py",
                    "required": true,
                    "condition" : {
                        "name": "ClientId",
                        "values": [ "VSCode"],
                        "operator": "IN"
                    }
                },
                {
                    "assignTo": "$(FUNCTION_NAME_INPUT)",
                    "paramId": "trigger-functionName",
                    "required": true,
                    "defaultValue": "dapr_service_invocation_trigger"
                }
            ],
            "actions": [
                "readFileContent_BlueprintFile",
                "writeFile_BlueprintFile",
                "readFileContent_BlueprintBody",
                "appendFileContent_BlueprintBody"
            ]
        },
        {
            "name": "Add DaprServiceInvocationTrigger function to the Blueprint",
            "type": "AppendToBlueprint",
            "inputs": [
                {
                    "assignTo": "$(APP_FILENAME)",
                    "paramId": "app-fileName",
                    "required": true,
                    "condition" : {
                        "name": "ClientId",
                        "values": [ "VSCode"],
                        "operator": "IN"
                    }
                },
                {
                    "assignTo": "$(FUNCTION_NAME_INPUT)",
                    "paramId": "trigger-functionName",
                    "required": true,
                    "defaultValue": "dapr_service_invocation_trigger"
                }
            ],
            "actions": [
                "readFileContent_BlueprintBody",
                "appendFileContent_BlueprintBody"
            ]
        }
    ],
    "actions": [
        {
            "name": "readFileContent_FunctionApp",
            "type": "GetTemplateFileContent",
            "assignTo": "$(FUNCTION_APP_CONTENT)",
            "filePath": "function_app.py"
        },
        {
            "name": "writeFile_FunctionApp",
            "type": "WriteToFile",
            "source": "$(FUNCTION_APP_CONTENT)",
            "filePath": "$(APP_FILENAME)",
            "continueOnError": false,
            "errorText": "Unable to create the function app",
            "replaceTokens": true,
            "FileExtension": ".py"
        },
        {
            "name": "readFileContent_FunctionBody",
            "type": "GetTemplateFileContent",
            "assignTo": "$(FUNCTION_BODY)",
            "filePath": "function_body.py"
        },
        {
            "name": "appendFileContent_FunctionApp",
            "type": "AppendToFile",
            "createIfNotExists": false,
            "source": "$(FUNCTION_BODY)",
            "filePath": "$(SELECTED_FILEPATH)",
            "continueOnError": false,
            "errorText": "Unable to create dapr service invocation trigger function",
			"replaceTokens": true,
            "FileExtension": ".py"
        },
        {
            "name": "ShowMarkdownPreview",
            "type": "ShowMarkdownPreview",
            "filePath": "dapr_service_invocation_trigger_template.md"
        },
        {
            "name": "readFileContent_BlueprintFile",
            "type": "GetTemplateFileContent",
            "assignTo": "$(BLUEPRINT_CONTENT)",
            "filePath": "blueprint.py"
        },
        {
            "name": "writeFile_BlueprintFile",
            "type": "WriteToFile",
            "source": "$(BLUEPRINT_CONTENT)",
            "filePath": "$(BLUEPRINT_FILENAME)",
            "continueOnError": false,
            "errorText": "Unable to create blueprint",
            "replaceTokens": true,
            "FileExtension": ".py"
        },
        {
            "name": "readFileContent_BlueprintBody",
            "type": "GetTemplateFileContent",
            "assignTo": "$(BLUEPRINT_BODY_CONTENT)",
            "filePath": "blueprint_body.py"
        },
        {
            "name": "appendFileContent_BlueprintBody",
            "type": "AppendToFile",
            "source": "$(BLUEPRINT_BODY_CONTENT)",
            "filePath": "$(BLUEPRINT_FILENAME)",
            "continueOnError": false,
            "errorText": "Unable to create the Blueprint",
            "replaceTokens": true,
            "FileExtension": ".py"
        }
    ]
}
